name: Linting

on:
  push:
    branches-ignore: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'

      - run: npm install

      - name: Run the lint script
        run : npm run lint

